name: vkycenv
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - opencv
  - dlib
  - flask
  - flask-cors
  - streamlit
  - streamlit-webrtc
  - face_recognition
  - pytesseract
  - fpdf
  - xlsxwriter
  - sqlalchemy
  - requests
  - python-dotenv
  - ffmpeg
  - pip:
      - openai
      - boto3
      - s3transfer
      - pyjwt
